version: 2.1
orbs:
  composer: stockfiller/composer@2.0.4

jobs:
  build:
    docker:
      - image: cimg/php:8.2.7

    steps:
      - checkout
      - composer/install
  test:
    docker:
      - image: cimg/php:8.2.7

    steps:
      - run: composer test
